name: .NET 5 CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    name: .NET 5 Application
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101' # Check for latest at link at .NET 5 download page
      - run: dotnet build
      - run: dotnet test
      - name: Publish
        run: dotnet publish
      - name: Upload WebApp1 Build Artifact
        uses: actions/upload-artifact@v2
        with:
         name: desktop
         path: D:\a\CertificatePasswordRecovery\CertificatePasswordRecovery\CertificatePasswordRecovery2\bin\Debug\net5.0-windows\publish\
       
